name: ci

on:
  push:
    branches:
      - main

jobs:
  determine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - id: cheese
        run: |
          cd cheeses/
          CHEESES=$(find * -type d -exec echo \"{}\" \; | paste -s -d, -)
          echo "::set-output name=names::[$CHEESES]"
    outputs:
     cheeses: ${{ steps.cheese.outputs.names }}
  docker-build:
    runs-on: ubuntu-latest
    needs: [determine]
    strategy:
      matrix:
        cheese: ${{ fromJSON(needs.determine.outputs.cheeses) }}
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: qemu_setup
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3
      - name: buildx_setup
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3
      - name: docker_login
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build docker image
        id: docker_build
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5
        with:
          push: true
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/386,linux/ppc64le,linux/s390x
          tags: boredland/cheese:${{ matrix.cheese }}
          build-args: |
            CHEESE=${{ matrix.cheese }}
